spring:
  datasource:
    url: jdbc:postgresql://deal-db:5432/credit-conveyor-db
  liquibase:
    url: jdbc:postgresql://deal-db:5432/credit-conveyor-db
  kafka:
    producer:
      bootstrap-servers: kafka:9092
feign:
  url:
    conveyor: 'http://conveyor:8080/conveyor'
