spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/credit-conveyor-db
    username: postgres
    password: 123456
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/credit-conveyor-db
    user: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

feign:
  url:
    conveyor: 'http://localhost:8082/conveyor'

topic:
  finish-registration: conveyor-finish-registration
  create-documents: conveyor-create-documents
  credit-issued: conveyor-credit-issued
  application-denied: conveyor-application-denied
  send-ses: conveyor-send-ses
  send-documents: conveyor-send-documents
