spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: #
    username: #
    password: #
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
    url: #
    user: #
    password: #
    driver-class-name: #
properties:
  feign:
    url: 'http://localhost:8080/conveyor'

topic:
  finish-registration: conveyor-finish-registration
  create-documents: conveyor-create-documents
  credit-issued: conveyor-credit-issued
  application-denied: conveyor-application-denied
  send-ses: conveyor-send-ses