feign:
  url:
    deal: "http://localhost:8080/deal"

sender:
  from:
    email: credit@ept.ru

email-message:
  send-document:
    subject: "Your loan documents"
    text: "Your loan documents are ready. Application {applicationId}. Send a request to sign documents"
  send-ses:
    subject: "Your Simple Electronic Signature (SES)"
    text: "Your SES code {sesCode} for your application {applicationId}. \n Submit the code here: LINK"
  create-document:
    subject: "Create documents"
    text: "Loan Application {applicationId}. Checks passed. Submit a request to create documents. LINK"
  credit-issued:
    subject: "Credit issued!"
    text: "The loan for your application {applicationId} has been issued"
  application-denied:
    subject: "Loan application rejected"
    text: "Application {applicationId} denied"
  finish-registration:
    subject: "Finish registration"
    text: "Loan application {applicationId} approved! Follow this link https://LINK"

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: dossier-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

topic:
  finish-registration: conveyor-finish-registration
  create-documents: conveyor-create-documents
  credit-issued: conveyor-credit-issued
  application-denied: conveyor-application-denied
  send-ses: conveyor-send-ses
  send-documents: conveyor-send-documents

document:
  text:
    contract: |
      Credit contract {creditId} from {creditDate}
      Client's full name: {clientFullName}
      Client's passport: {clientPassport}
      Credit Info: 
        amount: {creditAmount}
        term: {creditTerm}
        monthly payment: {monthlyPayment}
        rate: {rate}
        psk: {psk}
        services:
          insurance: {isInsuranceEnabled}
          salary client: {isSalaryClient}
    loan-payment-schedule: |
      Payment schedule for credit contract {creditId} from {applicationCreationDate}
      Client's full name: {clientFullName}
      Payment schedule:
        {paymentSchedule}
    credit-application: |
      Credit application {applicationId} from {applicationCreationDate}
      Client info:
        full name: {clientFullName}
        birthdate: {clientBirthdate}
        gender: {clientGender}
        passport: {clientPassport}
        email: {clientEmail}
        martial status: {clientMartialStatus}
        dependent amount: {clientDependentAmount}
        Employment:
          employment status: {employmentStatus}
          employer INN (if present): {employerINN}
          salary: {employmentSalary}
          employment position: {employmentPosition}
          total work experience: {employmentWorkExperienceTotal}
          current work experience: {employmentWorkExperienceCurrent}